// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qirvnledqgwztaxdbatz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpcnZubGVkcWd3enRheGRiYXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzI3MjIsImV4cCI6MjA2NzAwODcyMn0._19DRlJ9-hV3b5MHHUHfGE88u5LjtrV8eWa-E9J57Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});